on:
  push:
    branches:
      - master
    paths-ignore:
      - "server/**"
      - "client/target/**"
      - "client/test/**"
      - "README.md"
      - "client/README.md"
      - ".gitignore"

name: Build_NewBank_Client

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - run: |
          cd client
          docker build -t gabrielbcn/newbankclient:1.0 .
          docker run --rm --entrypoint cat gabrielbcn/newbankclient:1.0  /target/newbankclient-1.0-SNAPSHOT-jar-with-dependencies.jar > newbankclient.jar
