on:
  push:
    branches:
      - master
    paths-ignore:
      - "server/**"
      - "client/target/**"
      - "client/test/**"
      - "README.md"
      - "client/README.md"
      - ".gitignore"
      - ".github/workflows/server.yml"
      - ".github/workflows/clientrelease.yml"

name: Build-Client-Offer-Artifact

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: "Build the JavaFX Client Application JAR"
        run: |
          cd client
          docker build -t gabrielbcn/newbankclient:1.0 .
          docker create -it --name temp gabrielbcn/newbankclient:1.0 sh
          docker cp temp:/target/newbankclient-1.0-SNAPSHOT-jar-with-dependencies.jar .
          mv newbankclient-1.0-SNAPSHOT-jar-with-dependencies.jar newbankclient.jar
          pwd
          ls -l

      - name: "Upload the JavaFX Client Application JAR as artifact in GitHub Action"
        uses: actions/upload-artifact@v2
        with:
          path: /home/runner/work/NewBank/NewBank/client/newbankclient.jar
