on:
  release:
    types: [created, published, prereleased, released]

name: Build_NewBank_Client

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - run: |
          cd client
          docker build -t gabrielbcn/newbankclient:1.0 .
          docker run --rm --entrypoint cat gabrielbcn/newbankclient:1.0  /target/newbankclient-1.0-SNAPSHOT-jar-with-dependencies.jar > newbankclient.jar

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: newbankclient.jar application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
