on:
  push:
    branches:
      - master
    paths-ignore:
      - "server/**"
      - "client/target/**"
      - "client/test/**"
      - "README.md"
      - "client/README.md"
      - ".gitignore"

name: Build_NewBank_Client

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - run: |
          cd client
          docker build -t gabrielbcn/newbankclient:1.0 .
          docker create -it --name temp gabrielbcn/newbankclient:1.0 sh
          docker cp temp:/target/newbankclient-1.0-SNAPSHOT-jar-with-dependencies.jar .
          mv newbankclient-1.0-SNAPSHOT-jar-with-dependencies.jar newbankclient.jar
          ls -l

      - uses: actions/upload-artifact@v2
        with:
          path: newbankclient.jar
