on: 
  release: 
    types: [created]

name: Build-Client-add-to-Release

jobs:
  build-and-add-to-release:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - run: |
          cd client
          docker build -t gabrielbcn/newbankclient:1.0 .
          docker create -it --name temp gabrielbcn/newbankclient:1.0 sh
          docker cp temp:/target/newbankclient-1.0-SNAPSHOT-jar-with-dependencies.jar .
          mv newbankclient-1.0-SNAPSHOT-jar-with-dependencies.jar newbankclient.jar
          pwd
          ls -l
          
      - uses: actions/upload-artifact@v2
        with:
          path: newbankclient.jar

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: client/newbankclient.jar application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}