# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Creating the container
    - name: Creating the container
      run: |
        cd server
        echo "Building the container in two stages"
        docker build -t gabrielbcn/newbankserver:1.0 .
        
     # Showing the outcome
    - name: Storing the image
      run: |
        echo "Listing images"
        docker images
        echo "Running the container"
        docker run -it -p 8080:14002 gabrielbcn/newbankserver:1.0
        echo "Actions done"
        
